# Your Name or Company
title: Onur KIZILARSLAN

# Description of your website. This is used for social sharing.
description:  The beautiful website of artist, poet, craftsperson, cyclist, and avid juggler, Uni Kravitz.

# A brief blurb about yourself
content: Merhabalar, GitHub sayfama hoş geldiniz. Burada, yapmış olduğum projelerimi sizlerle paylaşacağım. Hakkımda detaylı bilgiye blog hesabımdan ulaşabilirsiniz.
         <br> Hello and welcome to my GitHub page. Here, I will share my projects with you. You can find detailed information about me on my blog.</br>
# Add your social links
social:
  - platform: blog
    url: https://imonur.github.io/blog
  - platform: eğitim
    url: http://facadium.com.tr/
  - platform: mağaza
    url: https://www.stemkits.net/
  - platform: facebook
    url: https://www.facebook.com/facadium
  - platform: instagram
    url: https://www.instagram.com/facadium/
  - platform: linkedin
    url: https://www.linkedin.com/in/onur-kizilarslan/
  - platform: mail
    email: mailto:info@facadium.com.tr

# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
markdown: kramdown
sharing_image: card-lg.jpg
google_analytics: "UA-58263416-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: center

# Full layout
full_text_position: center # left, right or center
